'use client'

import { useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Mail, Eye, Clock, TrendingUp, AlertTriangle, CheckCircle2 } from 'lucide-react'

export function EmailNativeBriefings() {
  const [view, setView] = useState<'preview' | 'settings'>('preview')

  return (
    <Card className="border-2">
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-full bg-primary/10 flex items-center justify-center">
              <Mail className="size-5 text-primary" />
            </div>
            <div>
              <h3 className="text-lg font-semibold">Email Briefings</h3>
              <p className="text-sm text-muted-foreground">Auto-delivered to stakeholders</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button 
              variant={view === 'preview' ? 'default' : 'outline'} 
              size="sm"
              onClick={() => setView('preview')}
            >
              <Eye className="size-4 mr-2" />
              Preview
            </Button>
            <Button 
              variant={view === 'settings' ? 'default' : 'outline'} 
              size="sm"
              onClick={() => setView('settings')}
            >
              Settings
            </Button>
          </div>
        </div>

        {view === 'preview' && (
          <div className="space-y-4">
            <div className="border-2 rounded-lg overflow-hidden bg-white text-gray-900">
              {/* Email preview styled to look like actual email */}
              <div className="bg-gray-50 p-4 border-b text-sm">
                <div className="font-semibold mb-1">Weekly Project Brief: Mercy Valley EHR</div>
                <div className="text-gray-600">To: Sarah Chen (CFO) • Monday 8:00 AM</div>
              </div>
              
              <div className="p-6 space-y-4 text-sm">
                <div>
                  <div className="font-semibold mb-2">Hi Sarah,</div>
                  <div className="text-gray-700 leading-relaxed">
                    Here's your weekly executive summary for the Mercy Valley EHR implementation. Three key updates require your attention this week.
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <TrendingUp className="size-5 text-emerald-700" />
                      <span className="font-semibold text-emerald-900">Budget Performance</span>
                    </div>
                    <div className="text-gray-700">
                      Project is 42% complete at 38% budget spend - running $180K under baseline. Q3 contingency remains intact at $420K.
                    </div>
                  </div>

                  <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <AlertTriangle className="size-5 text-amber-700" />
                      <span className="font-semibold text-amber-900">Action Required</span>
                    </div>
                    <div className="text-gray-700 mb-2">
                      Q3 contractor budget increase needed: $85K for additional developer capacity. ROI: Prevents 4-week timeline slip worth $340K in delayed benefits.
                    </div>
                    <Button size="sm" className="bg-amber-600 hover:bg-amber-700 text-white">
                      Approve $85K Budget
                    </Button>
                  </div>

                  <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <CheckCircle2 className="size-5 text-blue-700" />
                      <span className="font-semibold text-blue-900">Milestone Achieved</span>
                    </div>
                    <div className="text-gray-700">
                      Phase 2 development completed 3 days early. Vendor performance exceeding expectations (92% on-time delivery rate).
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t text-gray-600">
                  <div className="mb-2">Questions? Reply to this email or message me in Slack.</div>
                  <div className="text-xs text-gray-500">
                    This briefing was generated by Vantage based on real-time project data. 
                    <a href="#" className="text-blue-600 hover:underline ml-1">View full dashboard →</a>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-4 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <Clock className="size-4" />
                <span>Sends Monday 8:00 AM</span>
              </div>
              <div className="flex items-center gap-2">
                <Eye className="size-4" />
                <span>87% open rate</span>
              </div>
              <div className="flex items-center gap-2">
                <TrendingUp className="size-4" />
                <span>CFO-optimized content</span>
              </div>
            </div>
          </div>
        )}

        {view === 'settings' && (
          <div className="space-y-4">
            <div className="space-y-3">
              <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                <div>
                  <div className="font-medium">CFO - Sarah Chen</div>
                  <div className="text-sm text-muted-foreground">Focus: Budget, ROI, financial risks</div>
                </div>
                <div className="text-sm text-success">Active</div>
              </div>

              <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                <div>
                  <div className="font-medium">CIO - Michael Torres</div>
                  <div className="text-sm text-muted-foreground">Focus: Architecture, technical decisions</div>
                </div>
                <div className="text-sm text-success">Active</div>
              </div>

              <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                <div>
                  <div className="font-medium">CEO - Jennifer Kim</div>
                  <div className="text-sm text-muted-foreground">Focus: Timeline, strategic risks</div>
                </div>
                <div className="text-sm text-success">Active</div>
              </div>
            </div>

            <Button className="w-full" variant="outline">
              + Add Stakeholder Briefing
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
